### ISSUE TITLE
Flusstools installs faulty on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by rengifoortega** [Ecohydraulics/flusstools-pckg#5]
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import flusstools as ft

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last): File "<stdin>", line 1, in <module>
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/__init__.py", line 7, in <module>
import lidartools
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/lidartools/__init__.py", line 1, in <module>
from .laspy_main import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/lidartools/laspy_main.py", line 6, in <module>
from .laspy_processor import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/lidartools/laspy_processor.py", line 1, in <module>
from .laspy_config import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/lidartools/laspy_config.py", line 3, in <module>
from .lastools_fun import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/lidartools/lastools_fun.py", line 6, in <module>
from fuzzycorr import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/fuzzycorr/__init__.py", line 1, in <module>
from .fuzzycorr import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/fuzzycorr/fuzzycorr.py", line 1, in <module>
from .fuzzycomp import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/fuzzycorr/fuzzycomp.py", line 9, in <module>
from .plotter import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/fuzzycorr/plotter.py", line 5, in <module>
from .prepro import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/fuzzycorr/prepro.py", line 9, in <module>
from geotools import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/geotools/__init__.py", line 1, in <module>
from .geotools import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/geotools/geotools.py", line 5, in <module>
from .srs_mgmt import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/geotools/srs_mgmt.py", line 1, in <module>
from .dataset_mgmt import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/geotools/dataset_mgmt.py", line 3, in <module>
gdal.UseExceptions()
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/osgeo/gdal.py", line 246, in UseExceptions
from . import gdal_array
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/osgeo/gdal_array.py", line 10, in <module>
from . import _gdal_array
AttributeError: _ARRAY_API not found

**Comment by rengifoortega** [comment]
This error is solved. Thanks  Sebastian !

**Comment by rengifoortega** [comment]
done.
