### ISSUE TITLE
Flusstools installs faulty on Ubuntu 22.04.4 LTS  - tabulate module not found

### ISSUE THREAD

**Issue by rengifoortega** [Ecohydraulics/flusstools-pckg#6]
I just gave a try in my new linux and it failed. This time with a new error: Python 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flusstools as ft
Traceback (most recent call last):
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/import_mgmt.py", line 15, in <module>
from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/__init__.py", line 6, in <module>
from helpers import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/helpers.py", line 2, in <module>
from var_config import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/var_config.py", line 2, in <module>
from import_mgmt import *
File "/home/tlo/Desktop/vflussenv/lib/python3.10/site-packages/flusstools/import_mgmt.py", line 17, in <module>
raise ImportError("Could not import standard libraries:\n{0}".format(e))
ImportError: Could not import standard libraries:
No module named 'tabulate'

**Comment by sschwindt** [comment]
The dependencies were upgraded for newer Ubuntu (derivatives). However, I could only test with Mint. Please let me know if the error persists.
